  export const Governorates = [
    { label: "cairo"},
    { label: "giza"},
    { label: "alexandria"},
    { label: "dakahlia"},
    { label: "red_sea" },
    { label: "beheira"},
    { label: "gharbia"},
    { label: "port_said"},
    { label: "suez"},
    { label: "ismailia"},
    { label: "kafr_el_sheikh" },
    { label: "sharqia"},
    { label: "qalyubia"},
    { label: "damietta"},
    { label: "matrouh" },
    { label: "minya"},
    { label: "beni_suef" },
    { label: "fayoum"},
    { label: "menoufia"},
    { label: "luxor"},
    { label: "asyut"},
    { label: "sohag"},
    { label: "qena"},
    { label: "aswan"},
    { label: "north_sinai" },
    { label: "south_sinai" },
    { label: "new_valley"}
  ];
